# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca029ab92b3bb988d0334a75b602095dfcf626383c3b83507c1a2f9208d95dba9d7871b26eadb55df7f854897c1c71f5e11fd8bfc31e42d2d62b02fb805ee2cc

test:
  secret_key_base: 4bbb9c414f5f114706fed324121eb6e904fa5e382032975028b068246e494226fd8390f16ee5eef3c305e8333d6a6f3c2a54cfede4fc5b1a3ddc989aa6be0678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
